/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_split_out_3 (
    input clk,
    input rst,
    input [15:0] split_chosen,
    output reg [6:0] seg_tolight,
    output reg [1:0] dig_tolight
  );
  
  
  
  wire [7-1:0] M_seg_display_seg;
  wire [2-1:0] M_seg_display_sel;
  reg [10-1:0] M_seg_display_values;
  multi_seven_seg_9 seg_display (
    .clk(clk),
    .rst(rst),
    .values(M_seg_display_values),
    .seg(M_seg_display_seg),
    .sel(M_seg_display_sel)
  );
  
  always @* begin
    seg_tolight = 1'h0;
    dig_tolight = 1'h0;
    M_seg_display_values = 10'h000;
    
    case (split_chosen)
      5'h00: begin
        M_seg_display_values = 10'h000;
      end
      5'h01: begin
        M_seg_display_values = 10'h020;
      end
      5'h02: begin
        M_seg_display_values = 10'h040;
      end
      5'h03: begin
        M_seg_display_values = 10'h060;
      end
      5'h04: begin
        M_seg_display_values = 10'h080;
      end
      5'h05: begin
        M_seg_display_values = 10'h0a0;
      end
      5'h06: begin
        M_seg_display_values = 10'h0c0;
      end
      5'h07: begin
        M_seg_display_values = 10'h0e0;
      end
      5'h08: begin
        M_seg_display_values = 10'h100;
      end
      5'h09: begin
        M_seg_display_values = 10'h120;
      end
      5'h0a: begin
        M_seg_display_values = 10'h020;
      end
      5'h0b: begin
        M_seg_display_values = 10'h021;
      end
      5'h0c: begin
        M_seg_display_values = 10'h022;
      end
      5'h0d: begin
        M_seg_display_values = 10'h023;
      end
      5'h0e: begin
        M_seg_display_values = 10'h024;
      end
      5'h0f: begin
        M_seg_display_values = 10'h025;
      end
      5'h10: begin
        M_seg_display_values = 10'h1a1;
      end
      5'h11: begin
        M_seg_display_values = 10'h1a2;
      end
      5'h12: begin
        M_seg_display_values = 10'h280;
      end
      default: begin
        M_seg_display_values = 10'h3ff;
      end
    endcase
    seg_tolight = ~M_seg_display_seg;
    dig_tolight = ~M_seg_display_sel;
  end
endmodule
