/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_10 (
    input [7:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs = 7'h08;
      end
      1'h1: begin
        segs = 7'h5e;
      end
      2'h2: begin
        segs = 7'h11;
      end
      2'h3: begin
        segs = 7'h12;
      end
      3'h4: begin
        segs = 7'h46;
      end
      3'h5: begin
        segs = 7'h22;
      end
      3'h6: begin
        segs = 7'h20;
      end
      3'h7: begin
        segs = 7'h1e;
      end
      4'h8: begin
        segs = 7'h00;
      end
      4'h9: begin
        segs = 7'h02;
      end
      4'hd: begin
        segs = 7'h05;
      end
      4'he: begin
        segs = 7'h2d;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
