/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bool_16_8 (
    input [15:0] x,
    input [15:0] y,
    input [3:0] boolAlufn,
    output reg [15:0] boolOut
  );
  
  
  
  reg [15:0] temp;
  
  always @* begin
    
    case (boolAlufn)
      4'h0: begin
        temp = x | y;
      end
      4'h1: begin
        temp = x & y;
      end
      4'h2: begin
        temp = x ^ y;
      end
      4'h3: begin
        temp = x;
      end
      4'h4: begin
        temp = y;
      end
      4'h8: begin
        temp = ~(x | y);
      end
      4'h9: begin
        temp = ~(x & y);
      end
      4'ha: begin
        temp = ~(x & y);
      end
      4'hb: begin
        temp = ~x;
      end
      4'hc: begin
        temp = ~y;
      end
      default: begin
        temp = 16'h0000;
      end
    endcase
    boolOut = temp;
  end
endmodule
