/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comp_16_10 (
    input z,
    input v,
    input n,
    input [1:0] compAlufn,
    output reg [15:0] compOut
  );
  
  
  
  reg temp;
  
  always @* begin
    
    case (compAlufn)
      2'h1: begin
        temp = z;
      end
      2'h2: begin
        temp = n ^ v;
      end
      2'h3: begin
        temp = (n ^ v) | z;
      end
      default: begin
        temp = 1'h0;
      end
    endcase
    compOut[1+14-:15] = 15'h0000;
    compOut[0+0-:1] = temp;
  end
endmodule
